# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Administrador', 'Administrador')], default='Administrador', max_length=250),
            preserve_default=False,
        ),
    ]
