# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import project.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_point',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Puedes agregar una foto a tu punto de venta <br /> <small><small>Debe ser menor a 300kb</small></small>', null=True, upload_to=project.app.models.path_logos),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='pay_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
