# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170122_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_attrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.Product'), help_text='Nombre del producto en el ticket', max_length=30)),
                ('inventory', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0, help_text='Precio final con impuestos')),
                ('taxes', models.BooleanField(default=False, help_text='A este producto se le graba IVA?')),
                ('dynamic_price', models.BooleanField(default=False, help_text='Habilita esta opcion si el precio lo pueden cambiar los vendedores', verbose_name='Precio din\xe1mico')),
                ('bar_code', models.CharField(blank=True, default=None, max_length=35, null=True, verbose_name='Codigo de barras')),
                ('primary', models.BooleanField(default=False, help_text='Quieres resaltar este producto?')),
                ('active', models.BooleanField(default=True, help_text='Este producto esta activo?')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, help_text='Cantidad', max_length=250, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='product_recipe', to='app.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, help_text='Unidades', max_length=250, null=True, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='color',
            field=models.CharField(default='#5090c1', max_length=250, verbose_name='Color de los botones'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Este men\xfa depende de alg\xfan otro?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.Menu', verbose_name='Depende de?'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sellpoint',
            field=models.ManyToManyField(blank=True, to='app.Sell_point'),
        ),
        migrations.AddField(
            model_name='product_attrs',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
