# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import project.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170224_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Puedes asociar una imagen a cada producto <br /> <small><small>Debe ser menor a 300kb</small></small>', null=True, upload_to=project.app.models.path_image_product),
        ),
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Menu', verbose_name='Menu al que pertenece?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas')], help_text='Unidades', max_length=250, null=True, verbose_name='Unidades'),
        ),
    ]
