# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mptt.fields
import project.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170301_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sellpoint',
        ),
        migrations.AddField(
            model_name='product',
            name='sell_points',
            field=models.ManyToManyField(blank=True, related_name='product_sell_points', to='app.Sell_point'),
        ),
        migrations.AddField(
            model_name='product_attrs',
            name='sell_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs_points', to='app.Sell_point'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Puedes asociar una imagen a cada producto <br /> <small><small>Debe ser menor a 300kb</small></small>', null=True, upload_to=project.app.models.path_image_product, verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Este men\xfa depende de alg\xfan otro?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_menu', to='app.Menu', verbose_name='Depende de?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Introduce solo n\xfameros', null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.ManyToManyField(blank=True, help_text='Si tu producto se conforma de mas productos agregalos aqu\xed.', related_name='product_recipe', to='app.Product', verbose_name='Receta del producto'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='alias',
            field=models.CharField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs_points', to='app.Product'), help_text='Nombre del producto en el ticket', max_length=30),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs_points', to='app.Product'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='name',
            field=models.CharField(help_text='Ingresa un nombre para definir un Punto de Venta', max_length=250, verbose_name='Nombre del punto de venta'),
        ),
    ]
