# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170322_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Selecciona el men\xfa del que depende este producto.s', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_menu', to='app.Menu', verbose_name='Menu del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Introduce el nombre del producto', max_length=250, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_points',
            field=models.ManyToManyField(blank=True, related_name='product_sell_points', to='app.Sell_point', verbose_name='Se vende en:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas')], help_text='Selecciona el tipo de unidades', max_length=250, null=True, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='active',
            field=models.BooleanField(default=True, help_text='Este producto aparece en el sistema?', verbose_name='Esta activo?'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='alias',
            field=models.CharField(blank=True, help_text='Nombre del producto que aparecer\xe1 en el ticket', max_length=30, verbose_name='Alias del producto'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='dynamic_price',
            field=models.BooleanField(default=False, help_text='Habilita esta opci\xf3n si el precio lo pueden cambiar los vendedores', verbose_name='Precio din\xe1mico'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Cantidad de producto en el sistema', verbose_name='Inventario de producto en este punto de venta'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='price',
            field=models.FloatField(default=0, help_text='Precio final de venta al p\xfablico', verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='primary',
            field=models.BooleanField(default=False, help_text='Quieres resaltar este producto?', verbose_name='Es principal?'),
        ),
        migrations.AlterField(
            model_name='product_attrs',
            name='taxes',
            field=models.BooleanField(default=False, help_text='A este producto se le graba IVA?', verbose_name='I.V.A.'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='sell_point',
        ),
        migrations.AddField(
            model_name='user',
            name='sell_point',
            field=models.ManyToManyField(blank=True, null=True, to='app.Sell_point'),
        ),
    ]
