# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import project.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170323_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=project.app.models.pathuser_photo, verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor'), ('Vendedor autorizado para cobrar', 'Vendedor autorizado para cobrar'), ('Supervisor', 'Supervisor')], default='Vendedor', max_length=250, verbose_name='Tipo de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sell_point',
            field=models.ManyToManyField(blank=True, to='app.Sell_point', verbose_name='Asignado a Puntos de Venta:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visible_username',
            field=models.CharField(max_length=250, verbose_name='Nombre de Usuario'),
        ),
    ]
