# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import project.app.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170329_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_point',
            name='invoice',
            field=models.BooleanField(default=False, verbose_name='Emites Facturas?'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='sello',
            field=models.FileField(blank=True, null=True, upload_to=project.app.models.path_invoice, verbose_name='Sello fiscal para hacer facturas <small>(Solo si emites facturas)</small>'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='timbres',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
