# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170330_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_point',
            name='address_1',
            field=models.CharField(blank=True, help_text='1ra linea del ticket', max_length=250, null=True, verbose_name='Direccion Linea 1'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='address_2',
            field=models.CharField(blank=True, help_text='2da linea del ticket', max_length=250, null=True, verbose_name='Direccion Linea 2'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='address_3',
            field=models.CharField(blank=True, help_text='3ra linea del ticket', max_length=250, null=True, verbose_name='Direccion Linea 3'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='domain',
            field=models.CharField(blank=True, help_text='Dominio de la sucursal', max_length=250, null=True, verbose_name='Pagina Web'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='email',
            field=models.CharField(blank=True, help_text='Email de la sucursal', max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='phone',
            field=models.CharField(blank=True, help_text='Tel\xe9fono de la sucursal', max_length=250, null=True, verbose_name='Telefono'),
        ),
    ]
