# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170330_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_point',
            name='rfc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='address_1',
            field=models.CharField(blank=True, help_text='1ra linea del ticket', max_length=40, null=True, verbose_name='Direccion Linea 1'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='address_2',
            field=models.CharField(blank=True, help_text='2da linea del ticket', max_length=40, null=True, verbose_name='Direccion Linea 2'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='address_3',
            field=models.CharField(blank=True, help_text='3ra linea del ticket', max_length=40, null=True, verbose_name='Direccion Linea 3'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='domain',
            field=models.CharField(blank=True, help_text='Dominio de la sucursal', max_length=40, null=True, verbose_name='P\xe1gina Web'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='email',
            field=models.CharField(blank=True, help_text='Email de la sucursal', max_length=20, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='phone',
            field=models.CharField(blank=True, help_text='Tel\xe9fono de la sucursal', max_length=13, null=True, verbose_name='Tel\xe9fono'),
        ),
    ]
