# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170330_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuttime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('sell_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sell_point')),
            ],
        ),
        migrations.RemoveField(
            model_name='cut',
            name='code_sellpoint',
        ),
        migrations.AddField(
            model_name='cut',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
