# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170403_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='anticipe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
