# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170413_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='code_sellpoint',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
