# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cut_code_sellpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_point',
            name='nombre_fiscal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre Fiscal'),
        ),
        migrations.AddField(
            model_name='sell_point',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Regimen Fiscal'),
        ),
        migrations.AlterField(
            model_name='sell_point',
            name='invoice_domain',
            field=models.CharField(blank=True, help_text='Dominio de la sucursal para facturar', max_length=40, null=True, verbose_name='URL de Facturaci\xf3n'),
        ),
    ]
